"""Initial schema

Revision ID: a56a62960727
Revises: 
Create Date: 2026-02-03 12:41:48.309276

"""
import sqlalchemy as sa
from alembic import op

revision = 'a56a62960727'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lists_user_id', 'lists', ['user_id'], unique=False)
    op.create_table('recovery_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recovery_codes_user_id', 'recovery_codes', ['user_id'], unique=False)
    op.create_table('watch_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('last_position', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("media_type IN ('movie', 'tv', 'episode')", name='check_watch_history_media_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tmdb_id', 'media_type', 'season_number', 'episode_number', name='uq_watch_history_user_content')
    )
    op.create_index('idx_watch_history_user_id', 'watch_history', ['user_id'], unique=False)
    op.create_index('idx_watch_history_watched_at', 'watch_history', ['watched_at'], unique=False)
    op.create_table('list_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("media_type IN ('movie', 'tv')", name='check_list_items_media_type'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'tmdb_id', 'media_type', name='uq_list_items_list_content')
    )
    op.create_index('idx_list_items_list_id', 'list_items', ['list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_list_items_list_id', table_name='list_items')
    op.drop_table('list_items')
    op.drop_index('idx_watch_history_watched_at', table_name='watch_history')
    op.drop_index('idx_watch_history_user_id', table_name='watch_history')
    op.drop_table('watch_history')
    op.drop_index('idx_recovery_codes_user_id', table_name='recovery_codes')
    op.drop_table('recovery_codes')
    op.drop_index('idx_lists_user_id', table_name='lists')
    op.drop_table('lists')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
