"""add icon_url to lists

Revision ID: b78e4d2f1e60
Revises: a56a62960727
Create Date: 2026-02-04 09:18:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78e4d2f1e60'
down_revision: Union[str, None] = 'a56a62960727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('icon_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'icon_url')
    # ### end Alembic commands ###
